config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ######Sedentary Activities######

  get "/sedentaryactivities", to: "sedentary_activities#index", as: "sedentary_activities"
  get "/sedentaryactivities/new", to: "sedentary_activities#new", as: "new_sedentary_activity"
  get "/sedentaryactivities/:id", to: "sedentary_activities#show", as: "sedentary_activity"
  post "/sedentaryactivities", to: "sedentary_activities#create"
  get "/sedentaryactivities/:id/edit", to: "sedentary_activities#edit", as: "edit_sedentary_activity"
  patch "/sedentaryactivities/:id", to: "sedentary_activities#update"
  delete "/sedentaryactivities/:id", to: "sedentary_activities#destroy", as: "destroy_sedentary_activity"

  ######Exericses######
  get "/exercises", to: "exercises#index", as: "exercises"
  get "/exercises/new", to: "exercises#new", as: "new_exercise"
  get "/exercises/:id", to: "exercises#show", as: "exercise"
  post "/exercises", to: "exercises#create"
  get "/exercises/:id/edit", to: "exercises#edit", as: "edit_exercise"
  patch "/exercises/:id", to: "exercises#update"
  delete "/exercises/:id", to: "exercises#destroy", as: "destroy_exercise"

  ######Users######
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  get "/users/:id", to: "users#show", as: "user"
  post "/users", to: "users#create"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  ###### Ingredients ######
  get "/ingredients", to: "ingredients#index", as: "ingredients"
  get "/ingredients/new", to: "ingredients#new", as: "new_ingredient"
  get "/ingredients/:id", to: "ingredients#show", as: "ingredient"
  post "/ingredients", to: "ingredients#create"
  get "/ingredients/:id/edit", to: "ingredients#edit", as: "edit_ingredient"
  patch "/ingredients/:id", to: "ingredients#update"
  delete "/ingredients/:id", to: "ingredients#destroy"

  ###### Meals ######
  get "/meals", to: "meals#index", as: "meals"
  get "/meals/new", to: "meals#new", as: "new_meal"
  get "/meals/decision", to: "meals#decision"
  get "/meals/:id", to: "meals#show", as: "meal"
  post "/meals", to: "meals#create"
  get "/meals/:id/edit", to: "meals#edit", as: "edit_meal"
  patch "/meals/:id", to: "meals#update"
  delete "/meals/:id", to: "meals#destroy"
  get "/meals/new/stock", to: "meals#stock_meal", as: "stock_meal"

  ######Days######
  get "/days", to: "days#index", as: "days"
  get "/days/new", to: "days#new", as: "new_day"
  get "/days/add_sedentary_activity", to: "days#add_sedentary_activity", as: "add_sedentary_activity"
  get "/days/add_exercise", to: "days#add_exercise", as: "add_exercise"
  get "/days/add_meal", to: "days#add_meal", as: "add_meal"
  get "/days/add_snack", to: "days#add_snack", as: "add_snack"

  post "/days/create_sedentary_activity", to: "days#create_sedentary_activity", as: "create_sedentary_activity"
  post "/days/create_exercise", to: "days#create_exercise", as: "create_exercise"
  post "/days/create_meal", to: "days#create_meal", as: "create_meal"
  post "/days/create_snack", to: "days#create_snack", as: "create_snack"


  get "/days/:id", to: "days#show", as: "day"

  post "/days", to: "days#create"
  # get "/days/:id/edit", to: "days#edit", as: "edit_day"
  # patch "/days/:id", to: "days#update"
  # delete "/days/:id", to: "days#destroy", as: "destroy_day"

  ######Sessions######
  get "/", to: "sessions#new"
  get "/login", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"


  ###### dashboard ######
  get "/dashboard", to: "dashboards#index", as: "dashboard"

  ###### Snacks ######
  get "/snacks", to: "snacks#index", as: "snacks"
  get "/snacks/new", to: "snacks#new", as: "new_snack"
  get "/snacks/:id", to: "snacks#show", as: "snack"
  post "/snacks", to: "snacks#create"
  get "/snacks/:id/edit", to: "snacks#edit", as: "edit_snack"
  patch "/snacks/:id", to: "snacks#update"

end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :day_sedentary_activities
  has_many :sedentary_activities, through: :day_sedentary_activities
  has_many :day_exercises
  has_many :exercises, through: :day_exercises
  has_many :day_meals
  has_many :meals, through: :day_meals
  has_many :meal_ingredients, through: :meals
  has_many :ingredients, through: :meal_ingredients
  has_many :day_snacks
  has_many :snacks, through: :day_snacks

  def formatted
    self.diary_date.strftime("%A, %d %B %Y")
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :find_day, only: [:show, :edit, :update]
  before_action :belongs_to_current_user?, only: [:show]
  helper_method :activity_selection

  def index
    @days = current_user.days
  end

  def new
    if current_user.day_started?
      redirect_to day_path(current_user.days.last)
    else
      @day = Day.new
      @day.diary_date = Date.today
      @day.user_id = current_user.id
      @day.save
      # byebug
      redirect_to day_path(@day)
    end
  end

  def add_sedentary_activity
    @day = Day.find(params[:day])
  end

  def create_sedentary_activity
    @day = Day.find(params[:format])
    activity_selection
    redirect_to dashboard_path
  end

  def add_exercise
    @day = Day.find(params[:day])
  end

  def create_exercise
    @day = Day.find(params[:format])
    exercise_selection
    redirect_to dashboard_path
  end

  def add_meal
    @day = Day.find(params[:day])
  end

  def create_meal
    @day = Day.find(params[:format])
    meal_selection
    redirect_to dashboard_path
  end

  def add_snack
    @day = Day.find(params[:day])
  end

  def create_snack
    @day = Day.find(params[:format])
    snack_selection
    redirect_to dashboard_path
  end

  def show
  end

  def create
  end

  def edit
  end

  def update
  end

  private

  def find_day
    if params[:user]
      @day = Day.find(params[:user][:day_ids])
    else
      @day = Day.find(params[:id])
    end
  end

  def activity_selection
    activities = params[:day][:sedentary_activity_ids]
    activities.delete("")
    activities.map { |activity_id| @day.sedentary_activities << SedentaryActivity.find(activity_id) }
  end

  def exercise_selection
    exercises = params[:day][:exercise_ids]
    exercises.delete("")
    exercises.map { |exercise_id| @day.exercises << Exercise.find(exercise_id) }
  end

  def meal_selection
    meals = params[:day][:meal_ids]
    meals.delete("")
    meals.map { |meal_id| @day.meals << Meal.find(meal_id) }
  end

  def snack_selection
    snacks = params[:day][:snack_ids]
    snacks.delete("")
    snacks.map { |snack_id| @day.snacks << Snack.find(snack_id) }
  end

  def belongs_to_current_user?
    unless @day.user == current_user
      redirect_to days_path
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/add_exercise.html.erb
<div class="page-title">
    <h2>Add Exercise</h2>
</div>
<div class="form-group">
    <%= form_for @day, url: create_exercise_path(@day), method: :post do |f| %>
    <%= f.select :exercise_ids, options_for_select(Exercise.all.collect { |e| [ e.name, e.id ] }), {}, {:multiple => true, :class => "form-control", :style => "height:125px" } %><br><br>
    <div class="row">
        <div class="col" align="right">
            <%= f.submit "Add to Diary"%>
            <% end %>
        </div> 
   
        <div class="col">
            <%= button_to "Create New Exercise", new_exercise_path, method: :get %>
        </div>
    </div>
</div>

app/views/days/add_meal.html.erb
<div class="page-title">
    <h2>Add Meal</h2>
</div>
<div class="form-group">
<%= form_for @day, url: create_meal_path(@day), method: :post do |f| %>
       
        <%= f.select :meal_ids, options_for_select(Meal.all.collect { |m| [ m.name, m.id ] }), {}, {:multiple => true, :class => "form-control", :style => "height:125px" } %><br><br>
<div class="row">
        <div class="col" align="right">
        <%= f.submit "Add to Diary"%>
 
    <% end %>
    </div>
  <div class="col" align="center">
    <%= button_to "Quick Create Meal", new_meal_path, method: :get, params: {decision: "new"} %>
    </div>
     <div class="col">
    <%= button_to "Choose From Ingredients", stock_meal_path, method: :get, params: {decision: "selection"} %>
    </div>
</div>
</div>

app/views/days/add_sedentary_activity.html.erb
<div class="page-title">
    <h2>Add Sedentary Activity</h2>
</div>

<div class="form-group">
<%= form_for @day, url: create_sedentary_activity_path(@day), method: :post do |f| %>
       
        <%= f.select :sedentary_activity_ids, options_for_select(SedentaryActivity.all.collect { |s| [ s.name, s.id ] }), {}, {:multiple => true, :class => "form-control", :style => "height:125px" } %><br>

    <div class="row">
        <div class="col" align="right">
            <%= f.submit "Add to Diary"%>  <% end %> 
        </div> 

        <div class="col">
            <%= button_to "Create New Activity", new_sedentary_activity_path, method: :get %>
        </div>
   
   </div>
  </div>

app/views/days/add_snack.html.erb
<div class="page-title">
    <h2>Add Snack</h2>
</div>

<div class="form-group">
<%= form_for @day, url: create_snack_path(@day), method: :post do |f| %>
       
        <%= f.select :snack_ids, options_for_select(Snack.all.collect { |s| [ s.name, s.id ] }), {}, {:multiple => true, :class => "form-control", :style => "height:125px" } %><br><br>
 <div class="row">
        <div class="col" align="right">
        <%= f.submit "Add to Diary"%>

    <% end %>
</div> 
     <div class="col">
            <%= button_to "Create New Snack", new_snack_path, method: :get %>
        </div>
</div>

app/views/days/edit.html.erb
<h1>Days#edit</h1>
<p>Find me in app/views/days/edit.html.erb</p>

app/views/days/index.html.erb
<h2>See History</h2>

<% @days.each do |day| %>
<h4><%= link_to day.diary_date.strftime("%A, %d %B %Y"), day_path(day) %></h4>
<% end %>

<%= button_to "Start My Day", new_day_path, :method => :get %>

app/views/days/new.html.erb
<h1>New Day</h1>

app/views/days/show.html.erb
<div class="page-title">
    <h3>Diary for <%= @day.diary_date.strftime("%A, %d %B %Y") %></h3>
</div>
    <div>
      <%= button_to "Return to Dashboard", dashboard_path, :method => :get, class: 'btn btn-outline-secondary btn-lg btn-block ' %>
    </div>

<div class="container">
    <div class="row">
        <div class="days-boxes-left border rounded">
            <h3>Sedentary Activity</h3>
            <% if !@day.sedentary_activities.empty? %>
            <ul>
            <% @day.sedentary_activities.each do |activity| %>
                <li> <%= activity.name %> <span class="box-info">(<%= activity.duration %> mins | <%= activity.calories %> kcal)</span></li>
                <% end %>
            </ul>
            <% else %>
                <p>Too BAD! You didn't SLOUCH today!</p>
            <% end %>
            <%= button_to "Add Sedentary Activity", add_sedentary_activity_path,:method => :get, params: {day: @day.id} %>
        </div>

        <div class="days-boxes-right border rounded">
            <h3>Exercise</h3>
            <% if !@day.exercises.empty? %>
            <ul>
                <% @day.exercises.each do |exercise| %>
                <li> <%= exercise.name %>   <span class="box-info">(<%= exercise.duration %> mins | <%= exercise.calories %> kcal)</span></li>
                <% end %>
            </ul>
            <% else %>
                <p>Nice work, you've saved those precious calories!</p>
            <% end %>
            <%= button_to "Add Exercise", add_exercise_path,:method => :get, params: {day: @day.id} %>
        </div>

    <div class="w-100"></div>

        <div class="days-boxes-left border rounded">
            <h3>Meals</h3>
            <% if !@day.meals.empty? %>
            <ul>
                <% @day.meals.each do |meal| %>
                    <li><%= meal.name %><span class="box-info"> (<%= meal.total_calories %> kcal | Protein:<%= meal.total_protein %>g | Fat:<%= meal.total_fat %>g | Carbs: <%= meal.total_carbs %>g)</li>
                <% end %>
            </ul>
            <% else %>
                <p>Come on, why haven't you been piling on the pounds!</p>
            <% end %>
            <%= button_to "Add Meal", add_meal_path,:method => :get, params: {day: @day.id} %>
        </div>

        <div class="days-boxes-right border rounded">
            <h3>Snacks</h3>
            <% if !@day.snacks.empty? %>
            <ul>
                <% @day.snacks.each do |snack| %>
                  <li><%= snack.name %><span class="box-info"> (<%= snack.calories %> kcal | Protein:<%= snack.protein %>g | Fat:<%= snack.fat %>g | Carbs: <%= snack.carbs %>g)</li>
                <% end %>
            </ul>
            <% else %>
                <p>Come on, no snacks today?!</p>
            <% end %>
            <%= button_to "Add Snack", add_snack_path,:method => :get, params: {day: @day.id} %>
        </div>
    </div>
</div>