config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ######Sedentary Activities######

  get "/sedentaryactivities", to: "sedentary_activities#index", as: "sedentary_activities"
  get "/sedentaryactivities/new", to: "sedentary_activities#new", as: "new_sedentary_activity"
  get "/sedentaryactivities/:id", to: "sedentary_activities#show", as: "sedentary_activity"
  post "/sedentaryactivities", to: "sedentary_activities#create"
  get "/sedentaryactivities/:id/edit", to: "sedentary_activities#edit", as: "edit_sedentary_activity"
  patch "/sedentaryactivities/:id", to: "sedentary_activities#update"
  delete "/sedentaryactivities/:id", to: "sedentary_activities#destroy", as: "destroy_sedentary_activity"

  ######Exericses######
  get "/exercises", to: "exercises#index", as: "exercises"
  get "/exercises/new", to: "exercises#new", as: "new_exercise"
  get "/exercises/:id", to: "exercises#show", as: "exercise"
  post "/exercises", to: "exercises#create"
  get "/exercises/:id/edit", to: "exercises#edit", as: "edit_exercise"
  patch "/exercises/:id", to: "exercises#update"
  delete "/exercises/:id", to: "exercises#destroy", as: "destroy_exercise"

  ######Users######
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  get "/users/:id", to: "users#show", as: "user"
  post "/users", to: "users#create"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  ###### Ingredients ######
  get "/ingredients", to: "ingredients#index", as: "ingredients"
  get "/ingredients/new", to: "ingredients#new", as: "new_ingredient"
  get "/ingredients/:id", to: "ingredients#show", as: "ingredient"
  post "/ingredients", to: "ingredients#create"
  get "/ingredients/:id/edit", to: "ingredients#edit", as: "edit_ingredient"
  patch "/ingredients/:id", to: "ingredients#update"
  delete "/ingredients/:id", to: "ingredients#destroy"

  ###### Meals ######
  get "/meals", to: "meals#index", as: "meals"
  get "/meals/new", to: "meals#new", as: "new_meal"
  get "/meals/decision", to: "meals#decision"
  get "/meals/:id", to: "meals#show", as: "meal"
  post "/meals", to: "meals#create"
  get "/meals/:id/edit", to: "meals#edit", as: "edit_meal"
  patch "/meals/:id", to: "meals#update"
  delete "/meals/:id", to: "meals#destroy"
  get "/meals/new/stock", to: "meals#stock_meal", as: "stock_meal"

  ######Days######
  get "/days", to: "days#index", as: "days"
  get "/days/new", to: "days#new", as: "new_day"
  get "/days/add_sedentary_activity", to: "days#add_sedentary_activity", as: "add_sedentary_activity"
  get "/days/add_exercise", to: "days#add_exercise", as: "add_exercise"
  get "/days/add_meal", to: "days#add_meal", as: "add_meal"
  get "/days/add_snack", to: "days#add_snack", as: "add_snack"

  post "/days/create_sedentary_activity", to: "days#create_sedentary_activity", as: "create_sedentary_activity"
  post "/days/create_exercise", to: "days#create_exercise", as: "create_exercise"
  post "/days/create_meal", to: "days#create_meal", as: "create_meal"
  post "/days/create_snack", to: "days#create_snack", as: "create_snack"


  get "/days/:id", to: "days#show", as: "day"

  post "/days", to: "days#create"
  # get "/days/:id/edit", to: "days#edit", as: "edit_day"
  # patch "/days/:id", to: "days#update"
  # delete "/days/:id", to: "days#destroy", as: "destroy_day"

  ######Sessions######
  get "/", to: "sessions#new"
  get "/login", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"


  ###### dashboard ######
  get "/dashboard", to: "dashboards#index", as: "dashboard"

  ###### Snacks ######
  get "/snacks", to: "snacks#index", as: "snacks"
  get "/snacks/new", to: "snacks#new", as: "new_snack"
  get "/snacks/:id", to: "snacks#show", as: "snack"
  post "/snacks", to: "snacks#create"
  get "/snacks/:id/edit", to: "snacks#edit", as: "edit_snack"
  patch "/snacks/:id", to: "snacks#update"

end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :day_meals
  has_many :meal_ingredients
  has_many :ingredients, through: :meal_ingredients

  validates :name, uniqueness: true

  def calculate_nutrition_totals
    self.total_calories = self.ingredients.sum do |ingredient|
      ingredient.calories
    end
    self.total_protein = self.ingredients.sum do |ingredient|
      ingredient.protein
    end
    self.total_fat = self.ingredients.sum do |ingredient|
      ingredient.fat
    end
    self.total_carbs = self.ingredients.sum do |ingredient|
      ingredient.carbs
    end
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :is_admin?, only: [:index, :show, :edit]
  before_action :find_meal, only: [:show, :edit, :update, :destroy] 
  helper_method :ingredient_selection

  def index
    @meals = Meal.all
  end
  
  def decision
  end

  def new
    @meal = Meal.new
  end

  def stock_meal
    @meal = Meal.new
  end

  def show
  end

  def create
    @meal = Meal.new
    @day = current_user.get_current_date
      if params[:meal][:ingredient_ids]       
        @meal.name = params[:meal][:name]
        ingredient_selection
        @meal.calculate_nutrition_totals
        @meal.save
        redirect_to add_meal_path(current_user, day: @day.id)
      else
        @meal = Meal.new(meal_params)
        @meal.save
        redirect_to add_meal_path(current_user, day: @day.id)
      end
  end

  def edit
  end

  def update
    if @meal.ingredients[0]
        @meal.name = params[:meal][:name]
        @meal.ingredients = []
        ingredient_selection
        @meal.calculate_nutrition_totals
        @meal.save
    elsif @meal.ingredients.empty?
        @meal.update(meal_params)
    end

    if @meal.valid?
      redirect_to meal_path(@meal)
    else
      render :edit
    end
  end

  def destroy
    Meal.destroy(@meal.id)
    redirect_to meals_path
  end

  private

  def find_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:name, :total_calories, :total_protein, :total_fat, :total_carbs)
  end

  def ingredient_selection
    ingredients = params[:meal][:ingredient_ids]
    ingredients.delete("")
    ingredients.map {|ingredient_id| @meal.ingredients << Ingredient.find(ingredient_id)}
  end

end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<% if @meal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being created:</h2>
    <ul>
        <% @meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

<% if params[:decision] == "new" || @meal.ingredients.empty? && params[:action] == "edit" || @meal.ingredients.empty? && params[:action] == "update"%>

<div role="form" class="border rounded activity-form-aligned">
    <%= form_for @meal do |f| %>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name, required: true, class: 'form-control'  %>
        </div>
        <div>
            <%= f.label :total_calories %>
            <%= f.number_field :total_calories, required: true, class: 'form-control'  %>
        </div>
        <div>
            <%= f.label :total_protein %>
            <%= f.number_field :total_protein, required: true, class: 'form-control'  %>
        </div>
        <div>
            <%= f.label :total_fat %>
            <%= f.number_field :total_fat, required: true, class: 'form-control'  %>
        </div>
        <div>
            <%= f.label :total_carbohydrate %>
            <%= f.number_field :total_carbs, required: true, class: 'form-control'  %>
        </div>
        <br>
        <div>
            <%= f.submit %>
        </div>
    <% end %>
    </div>
<% elsif params[:decision] == "selection"|| @meal.ingredients && params[:action] == "edit" || @meal.ingredients && params[:action] == "update"%>


<div role="form" class="border rounded activity-form-aligned">
    <%= form_for @meal do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, required: true , class: 'form-control'%><br>
        <%= f.label :ingredient %>
        <%= f.select :ingredient_ids, options_for_select(Ingredient.all.collect { |i| [ i.name, i.id ] }), {}, {:multiple => true, required: true, :class => "form-control", :style => "height:125px" } %><br>
        <%= f.submit %>
    <% end %>
<% end %>
  </div>

app/views/meals/decision.html.erb
<h2>How would you like to create a new Meal</h2>

<%= button_to "Create A Custom Meal", new_meal_path, method: :get, params: {decision: "new"} %>
<%= button_to "Pick From Current Ingredients List", stock_meal_path, method: :get, params: {decision: "selection"} %>

app/views/meals/edit.html.erb
<h2>Edit Meal: <%= @meal.name %></h2>

<%= render 'form', meal: @meal  %>

<%= button_to "Return to See all Meals", meals_path, method: :get %>

app/views/meals/index.html.erb
<h2>All available Meals</h2>

<% @meals.each do |meal| %>
<h3><%= link_to meal.name, meal_path(meal)%></h3>
<h4>Total: Calories <%= meal.total_calories %>kcal | Protein <%= meal.total_protein %>g | Fat <%= meal.total_fat %>g | Carbohydrate <%= meal.total_carbs %>g</h4>
    <% unless meal.ingredients.empty? %>
        <h4>Ingredients:</h4>
        <ul>
            <% meal.ingredients.each do |ingredient| %>
            <%# <li><%= link_to ingredient.name, ingredient_path(ingredient) %>
            <li><%= ingredient.name %></li>
            <% end %>
        </ul>
    <% end %>
<% end %>

app/views/meals/new.html.erb
<div class="page-title">
<h2>Create New Meal</h2>
</div>

<%= render 'form' , meal: @meal %>

app/views/meals/show.html.erb
<h2><%= @meal.name %></h2>

<h3>Nutritional Breakdown</h3>
<h5>Calories: <%= @meal.total_calories %>kcal</h5>
<h5>Protein: <%= @meal.total_protein %>g</h5>
<h5>Fat: <%= @meal.total_fat %>g</h5>
<h5>Carbohydrate: <%= @meal.total_carbs %>g</h5>

<% unless @meal.ingredients.empty? %>
    <h3>Ingredients</h3>
    <ul>
        <% @meal.ingredients.each do |ingredient| %>
        <li><%= ingredient.name %></li>
        <% end %>
    </ul>
<% end %>
<%= link_to "Edit Meal", edit_meal_path(@meal) %> | <%= link_to "Delete Meal", meal_path(@meal), method: :delete %>

<%= button_to 'Return to See all Meals', meals_path, method: :get %>

app/views/meals/stock_meal.html.erb
<div class="page-title">
    <h2>Create New Meal</h2>
</div>

<%= render 'form', meal: @meal  %>