config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ######Sedentary Activities######

  get "/sedentaryactivities", to: "sedentary_activities#index", as: "sedentary_activities"
  get "/sedentaryactivities/new", to: "sedentary_activities#new", as: "new_sedentary_activity"
  get "/sedentaryactivities/:id", to: "sedentary_activities#show", as: "sedentary_activity"
  post "/sedentaryactivities", to: "sedentary_activities#create"
  get "/sedentaryactivities/:id/edit", to: "sedentary_activities#edit", as: "edit_sedentary_activity"
  patch "/sedentaryactivities/:id", to: "sedentary_activities#update"
  delete "/sedentaryactivities/:id", to: "sedentary_activities#destroy", as: "destroy_sedentary_activity"

  ######Exericses######
  get "/exercises", to: "exercises#index", as: "exercises"
  get "/exercises/new", to: "exercises#new", as: "new_exercise"
  get "/exercises/:id", to: "exercises#show", as: "exercise"
  post "/exercises", to: "exercises#create"
  get "/exercises/:id/edit", to: "exercises#edit", as: "edit_exercise"
  patch "/exercises/:id", to: "exercises#update"
  delete "/exercises/:id", to: "exercises#destroy", as: "destroy_exercise"

  ######Users######
  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  get "/users/:id", to: "users#show", as: "user"
  post "/users", to: "users#create"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  ###### Ingredients ######
  get "/ingredients", to: "ingredients#index", as: "ingredients"
  get "/ingredients/new", to: "ingredients#new", as: "new_ingredient"
  get "/ingredients/:id", to: "ingredients#show", as: "ingredient"
  post "/ingredients", to: "ingredients#create"
  get "/ingredients/:id/edit", to: "ingredients#edit", as: "edit_ingredient"
  patch "/ingredients/:id", to: "ingredients#update"
  delete "/ingredients/:id", to: "ingredients#destroy"

  ###### Meals ######
  get "/meals", to: "meals#index", as: "meals"
  get "/meals/new", to: "meals#new", as: "new_meal"
  get "/meals/decision", to: "meals#decision"
  get "/meals/:id", to: "meals#show", as: "meal"
  post "/meals", to: "meals#create"
  get "/meals/:id/edit", to: "meals#edit", as: "edit_meal"
  patch "/meals/:id", to: "meals#update"
  delete "/meals/:id", to: "meals#destroy"
  get "/meals/new/stock", to: "meals#stock_meal", as: "stock_meal"

  ######Days######
  get "/days", to: "days#index", as: "days"
  get "/days/new", to: "days#new", as: "new_day"
  get "/days/add_sedentary_activity", to: "days#add_sedentary_activity", as: "add_sedentary_activity"
  get "/days/add_exercise", to: "days#add_exercise", as: "add_exercise"
  get "/days/add_meal", to: "days#add_meal", as: "add_meal"
  get "/days/add_snack", to: "days#add_snack", as: "add_snack"

  post "/days/create_sedentary_activity", to: "days#create_sedentary_activity", as: "create_sedentary_activity"
  post "/days/create_exercise", to: "days#create_exercise", as: "create_exercise"
  post "/days/create_meal", to: "days#create_meal", as: "create_meal"
  post "/days/create_snack", to: "days#create_snack", as: "create_snack"


  get "/days/:id", to: "days#show", as: "day"

  post "/days", to: "days#create"
  # get "/days/:id/edit", to: "days#edit", as: "edit_day"
  # patch "/days/:id", to: "days#update"
  # delete "/days/:id", to: "days#destroy", as: "destroy_day"

  ######Sessions######
  get "/", to: "sessions#new"
  get "/login", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"


  ###### dashboard ######
  get "/dashboard", to: "dashboards#index", as: "dashboard"

  ###### Snacks ######
  get "/snacks", to: "snacks#index", as: "snacks"
  get "/snacks/new", to: "snacks#new", as: "new_snack"
  get "/snacks/:id", to: "snacks#show", as: "snack"
  post "/snacks", to: "snacks#create"
  get "/snacks/:id/edit", to: "snacks#edit", as: "edit_snack"
  patch "/snacks/:id", to: "snacks#update"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :days
  has_many :day_sedentary_activities, through: :days
  has_many :sedentary_activities, through: :day_sedentary_activities
  has_many :day_exercises, through: :days
  has_many :exercises, through: :day_exercises
  has_many :day_meals, through: :days
  has_many :meals, through: :day_meals
  has_many :meal_ingredients, through: :meals
  has_many :ingredients, through: :meal_ingredients
  has_many :day_snacks, through: :days
  has_many :snacks, through: :day_snacks

  validates :username, uniqueness: true, presence: true
  validates :age, numericality: { greater_than: 17, less_than: 110 }
  validates :password, length: { in: 6..20 }
  validates :height, numericality: { greater_than: 90, less_than: 210 }
  validates :weight, numericality: { greater_than: 65, less_than: 500 }

  has_secure_password

  def first_name
    self.name.split(" ").first
  end

  def day_started?
    self.days.any? { |day| day.diary_date == DateTime.now.to_date }
  end

  def get_current_date
    self.days.select { |day| day.diary_date == DateTime.now.to_date }.first
  end

  def macros_consumed_for_meals
    macros = []
    macros << self.get_current_date.meals.sum { |meal| meal.total_protein }
    macros << self.get_current_date.meals.sum { |meal| meal.total_fat }
    macros << self.get_current_date.meals.sum { |meal| meal.total_carbs }
    macros
  end

  def calories_consumed_for_meals
    self.get_current_date.meals.sum { |meal| meal.total_calories }
  end

  def macros_consumed_for_snacks
    macros = []
    macros << self.get_current_date.snacks.sum { |snack| snack.protein }
    macros << self.get_current_date.snacks.sum { |snack| snack.fat }
    macros << self.get_current_date.snacks.sum { |snack| snack.carbs }
    macros
  end

  def calories_consumed_for_snacks
    self.get_current_date.snacks.sum { |snack| snack.calories }
  end

  def combined_macros
    macros_consumed_for_meals.zip(macros_consumed_for_snacks).map { |v| v.reduce(:+) }
  end


  def calories_burned_through_sedentary
    self.get_current_date.sedentary_activities.sum { |sedentary| sedentary.calories }
  end

  def calories_burned_through_exercises
    self.get_current_date.exercises.sum { |exercise| exercise.calories }
  end

  def progress_bar
    if calories_consumed_for_meals > 0 || calories_consumed_for_snacks > 0
      percent = []
      calories_gained = calories_consumed_for_meals + calories_consumed_for_snacks
      calories_burned = calories_burned_through_sedentary + calories_burned_through_exercises
      total_calories = calories_burned + calories_gained
      percent << ((calories_gained.to_f/ total_calories.to_f)*100).round(0)
      percent << ((calories_burned.to_f / total_calories.to_f)*100).round(0)
      percent
    end
  end


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_exercise_dashboard.html.erb
<% if current_user.day_started? %>
<h4>Exercise <span class="calorie-info"> // <%= current_user.calories_burned_through_exercises%> kcal</span> </h4>

<% if !current_user.get_current_date.exercises.empty? %>
<ul>
    <% current_user.get_current_date.exercises.each do |exercise| %>
    <li> <%= exercise.name %></li>
    <% end %>
</ul>
<% else %>
    <p>Nice work, you've saved those precious calories!</p>
<% end %>
<% end %>

app/views/dashboards/_meal_dashboard.html.erb
<% if current_user.day_started? %>
<h4>Meals<span class="calorie-info"> // <%= current_user.calories_consumed_for_meals%> kcal | Protein: <%= current_user.macros_consumed_for_meals[0]%> | Fat: <%= current_user.macros_consumed_for_meals[1]%> | Carbs: <%= current_user.macros_consumed_for_meals[2] %></span></h4>

<% if !current_user.get_current_date.meals.empty? %>
<ul>
    <% current_user.get_current_date.meals.each do |meal| %>
        <li><%= meal.name %></li>
    <% end %>
</ul>
<% else %>
    <p>Come on, why haven't you been piling on the pounds! </p>
<% end %>
<% end %>

app/views/dashboards/_sedentary_dashboard.html.erb
<% if current_user.day_started? %>
  <h4>Sedentary Activity<span class="calorie-info"> // <%= current_user.calories_burned_through_sedentary%> kcal</span></h4>
  
  <% if !current_user.get_current_date.sedentary_activities.empty? %>
      <ul>
        <% current_user.get_current_date.sedentary_activities.each do |activity| %>
          <li> <%= activity.name %></li>
          <% end %>
      </ul>
  <% else %>
    <p>Too BAD! You didn't SLOUCH today!</p>
  <% end %>
<% end %>

app/views/dashboards/_snack_dashboard.html.erb
<% if current_user.day_started? %>
<h4>Snacks<span class="calorie-info"> // <%= current_user.calories_consumed_for_snacks%> kcal | Protein: <%= current_user.macros_consumed_for_snacks[0]%> | Fat: <%= current_user.macros_consumed_for_snacks[1]%> | Carbs: <%= current_user.macros_consumed_for_snacks[2] %></span></h4>

<% if !current_user.get_current_date.snacks.empty? %>
<ul>
    <% current_user.get_current_date.snacks.each do |ingredient| %>
        <li><%= ingredient.name %></li>
    <% end %>
</ul>
<% else %>
    <p>Come on, no snacks today?!</p>
<% end %>
<% end %>

app/views/dashboards/index.html.erb
<div class="page-title">
    <h2> <%= current_user.first_name %>'s Dashboard</h2>
</div>
<!-- Button-->
<div>
    <% if current_user.day_started? %>
         <%= button_to "Edit My Day", new_day_path, :method => :get, class: 'btn btn-secondary btn-lg btn-block' %>
    <% else %>
        <%= button_to "Start My Day", new_day_path, :method => :get, class: 'btn btn-primary btn-lg btn-block' %>
   <% end %>
</div>
<!-- Main Container-->


<% if current_user.day_started? %>
   
    <div class="container">
        <div class="row">
            <% if current_user.progress_bar %>
                <div class="col dash-boxes-single">
                    
                        <div class="progress">
                    
                            <div class="progress-bar bg-success" role="progressbar" style="width:<%= current_user.progress_bar[0] %>%">
                            Calories Gained
                            </div>
                            <div class="progress-bar bg-danger" role="progressbar" style="width:<%= current_user.progress_bar[1] %>%">
                            Calories Burned
                            </div>
                            
                        </div>
                </div>
            <% end %>  
            <div class="w-100"></div>
            <div class="col dash-boxes-left border rounded" align="center">
                <h4> Today's Macros </h4>
                    
            
                <%= pie_chart [["Protein: #{current_user.combined_macros[0]}g", current_user.combined_macros[0]], ["Fat: #{current_user.combined_macros[1]}g", current_user.combined_macros[1]], ["Carbs: #{current_user.combined_macros[2]}g", current_user.combined_macros[2]]], colors: ["#109618", "#dc3912", "#3366cc"], legend:"bottom", width:"45%", messages: {empty: "No data"} %>


                    
            </div>

            <div class="col dash-boxes-right border rounded" align="center">
               <h4> Activity Comparison </h4>
                
            
                <%= pie_chart [["Sedentary Activity: #{current_user.calories_burned_through_sedentary} kcal", current_user.calories_burned_through_sedentary], ["Exercise: #{current_user.calories_burned_through_exercises} kcal", current_user.calories_burned_through_exercises]], colors: ["#109618", "#dc3912"], legend:"bottom", width:"45%", messages: {empty: "No data"} %>

            </div>

        <div class="w-100"></div>
            <div class="col dash-boxes-left border rounded">
                <%= render "sedentary_dashboard" %>
            </div>

            <div class="col dash-boxes-right border rounded">
                <%= render "exercise_dashboard" %>
            </div>
        <div class="w-100"></div>
            <div class="col dash-boxes-left border rounded">
                <%= render "meal_dashboard" %>
            </div>

            <div class="col dash-boxes-right border rounded">
                <%= render "snack_dashboard" %>
            </div>

       </div>

    </div>

<% end %>

<% if current_user.days.count > 1 %>
<div class="dashboard-history border rounded">

    <h4>View History</h4>
    <%= form_tag day_path(:id), method: :get do %>
    <%= collection_select :user, :day_ids, @user.days, :id, :formatted %>
    <%= submit_tag "View Diary"%>
    <% end %>
</div>
<% end %>